INSERT INTO Bebidas
    (Indice_prod,
     Marca,
     Sabor,
     Indice_estoq,
     E_Alcolico)
VALUES
    ('Coca-Cola', 'Original', 1, FALSE),
    ('Coca-Cola', 'Zero', 2, FALSE),
    ('Pepsi', 'Original', 3, FALSE),
    ('Pepsi', 'Zero', 4, FALSE),
    ('Guaraná Antarctica', 'Original', 5, FALSE),
    ('Guaraná Antarctica', 'Zero', 6, FALSE),
    ('Fanta', 'Laranja', 7, FALSE),
    ('Fanta', 'Uva', 8, FALSE),
    ('Sprite', 'Original', 9, FALSE),
    ('Bonafont', 'Sem Gás', 10, FALSE),
    ('Crystal', 'Com Gás', 11, FALSE),
    ('Heineken', 'Original', 12, TRUE),
    ('Brahma', 'Original', 13, TRUE),
    ('Skol', 'Original', 14, TRUE),
    ('Budweiser', 'Original', 15, TRUE),
    ('Chá Lipton', 'Pêssego', 16, FALSE),
    ('Chá Lipton', 'Limão', 17, FALSE),
    ('Suco Del Valle', 'Laranja', 18, FALSE),
    ('Suco Del Valle', 'Uva', 19, FALSE),
    ('Red Bull', 'Original', 20, FALSE);